version: '3.8'

volumes:
  static:
  media:
  nginx_conf:

services:
  web:
    image: portfolio:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static:/static_root/
      - media:/media_root/
    ports:
      - "8000:8000"
    environment:
      DEBUG: '1'


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - nginx_conf:/nginx.conf
    depends_on:
      - web
    restart: always